Repository opdev/simple-java-operator, pull requests merged in 2023-05, with the labels that each got.

#2 cleanup targets, add dockerfile.jvm
  .gitignore
  Makefile
  pom.xml
  src/main/docker/Dockerfile.jvm
  src/main/resources/application.properties
  target/bundle/simple-java/bundle.Dockerfile
  target/bundle/simple-java/manifests/demoresources.tools.opdev.io-v1.crd.yml
  target/bundle/simple-java/manifests/simple-java.clusterserviceversion.yaml
  target/bundle/simple-java/metadata/annotations.yaml
  target/classes/application.properties
  target/kubernetes/demoresources.tools.opdev.io-v1.yml
  target/kubernetes/kubernetes.json
  target/kubernetes/kubernetes.yml
  target/test-classes/cr-test-demo-resource.yaml
Labels: size/XL

#6 busybox deployment yaml to apply during reconcile
  .gitignore
  Makefile
  hack/kubernetes.yml
  src/main/docker/Dockerfile.jvm
  src/main/java/io/opdev/DemoResourceReconciler.java
  src/main/resources/busybox-deploy.yaml
Labels: size/L, approved

#8 creating a kafka cluster from the simple demo operator (work in progress)
  README.md
  hack/kubernetes.yml
  src/main/docker/Dockerfile.jvm
  src/main/java/io/opdev/DemoResourceReconciler.java
  src/main/resources/amq-kafka-cluster.yaml
Labels: size/M

#9 cleanup makefile
  .gitignore
  Makefile
  bundle.Dockerfile
  hack/kubernetes.yml
Labels: size/S
